// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2T9dqGIuBAmakZYuymuBhracG6FzK9nA',
    appId: '1:906966661775:android:c445e94abbc6ba9ef90efa',
    messagingSenderId: '906966661775',
    projectId: 'team-project-be7e9',
    storageBucket: 'team-project-be7e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR2ngeZnvrczrcD3nRlfFCW2Bw_gYlye0',
    appId: '1:906966661775:ios:66b59c057ed9b3def90efa',
    messagingSenderId: '906966661775',
    projectId: 'team-project-be7e9',
    storageBucket: 'team-project-be7e9.appspot.com',
    iosClientId: '906966661775-poj0cn5gh3cjbl93rijlguhajh4go7ci.apps.googleusercontent.com',
    iosBundleId: 'com.example.appProject',
  );
}
